stages:
  - build
  - deploy
  - stop
build:
  stage: build
  tags:
    - linux
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "Building the application container..."
    - echo $CI_PROJECT_DIR
    - ls -la $CI_PROJECT_DIR
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo "CI_REGISTRY=$CI_REGISTRY CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE CI_COMMIT_SHA=$CI_COMMIT_SHA"
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy:
  stage: deploy
  dependencies:
    - build
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: dev
    url: https://ipearev-streamlit-dev.ipea.gov.br
    kubernetes:
      namespace: ipearev-streamlit
    on_stop: stop_app
  script:
    - kubectl config get-contexts
    - kubectl config use-context ipearev/k8s-agents:ipearev
    - echo "Deployment of image=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - echo "in namespace=ipearev-streamlit deployment=streamlit ..."
    - sed "s|__IMAGE__|${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}|g" deployment.yaml > /tmp/deployment.yaml
    - kubectl apply -f /tmp/deployment.yaml
    - kubectl rollout status deployment/streamlit --namespace=ipearev-streamlit --timeout=5m
    - echo "Creating service streamlit"
    - kubectl apply -f service.yaml
    - echo "Creating ingress streamlit for app=streamlit"
    - kubectl apply -f ingress.yaml
stop_app:
  stage: stop
  dependencies:
    - deploy
  variables:
    GIT_STRATEGY: none
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context ipearev/k8s-agents:ipearev
    - sed "s|__IMAGE__|${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}|g" deployment.yaml > /tmp/deployment.yaml
    - kubectl delete ingress -n ipearev-streamlit streamlit
    - kubectl delete service -n ipearev-streamlit streamlit
    - kubectl delete -f /tmp/deployment.yaml
  when: manual
  environment:
    name: dev
    kubernetes:
      namespace: ipearev-streamlit
    action: stop
