apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamlit
  namespace: ipearev-streamlit
spec:
  ingressClassName: nginx
  rules:
    - host: ipearev-streamlit-dev.ipea.gov.br
      http:
        paths:
          - backend:
              service:
                name: streamlit
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - ipearev-streamlit-dev.ipea.gov.br
      secretName: ipea-star-certificate
