apiVersion: v1
kind: Service
metadata:
  name: ipearev
  labels:
    app.kubernetes.io/name: ipearev
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ipearev
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
