apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: ipearev-streamlit
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8501
  selector:
    app: streamlit
  type: ClusterIP
